# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# Zubair's note - we're keeping this text. Might be useful for fachhas.
title: E-Cell, IIIT Hyderabad
email: ecell[at]iiit[dot]ac[dot]in
description: >- # this means to ignore newlines until "baseurl:"
  Turning ideas into reality is the sorcery that is best left to entrepreneurs.
  And we love helping out in spreading this art, because we believe that we need
  to realise and utilise the potential of the youth to reach new levels and open
  up new possibilities. For this we conduct numerous workshops, seminars, events
  and interactive sessions with eminent entrepreneurs, thus, providing the students
  exposure to the entrepreneurial world along with a platform to work on the live
  projects from start-ups.
baseurl: "ECell_build1" # the subpath of your site, e.g. /blog
url: "https://ecell.iiit.ac.in" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ecell_iiithyd
# paginate: 5
# paginate_path: "/blogs/page:num/"
# Build settings
markdown: kramdown
theme: minima
pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 5

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.
  title : ':title'




plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  #- octopress-paginate
fbcomments: yes


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
